LingmoOS/LingmoUI

- .github/workflows/doxygen-gh-pages.yml
> feat(doc): Create doxygen-gh-pages.yml

- example/CMakeLists.txt
- example/qml/global/SidebarItems.qml
- example/qml/main.qml
- example/qml/pages/Buttons.qml
- example/qml/pages/TabView.qml
- example/qml/windows/MainPage.qml
- example/qml/windows/MainWindow.qml
- src/Controls/LingmoBadge.qml
- src/Controls/LingmoControl.qml
- src/Controls/LingmoDivider.qml
- src/Controls/LingmoInfoBar.qml
- src/Controls/LingmoNavigationView.qml
- src/Controls/LingmoPage.qml
- src/Controls/LingmoPanelItem.qml
- src/Controls/LingmoPanelItemEmpty.qml
- src/Controls/LingmoPanelItemExpander.qml
- src/Controls/LingmoPanelItemHeader.qml
- src/Controls/LingmoPanelItemSeparator.qml
- src/Controls/LingmoProgressButton.qml
- src/Controls/LingmoScrollablePage.qml
- src/Controls/LingmoTabView.qml
- src/LingmoDefines.h
feature
- Tab View
- Scroll page
- Side navigation bar
No
> feat: add new components and update MainPage

- src/Controls/LingmoAcrylic.qml
- src/Controls/LingmoNavigationView.qml
- src/Controls/LingmoWindow.qml
- src/LingmoTools.cpp
Fix
- Blur area exceeds the rounded window
- Left panel's radius setting is missing
Fixed above issues.
> fix: improve blur and round corner effects

- example/qml/pages/TabView.qml
- src/Controls/LingmoTabView.qml
> feat(LingmoTabView): add properties and enhance example

- example/qml/pages/TabView.qml
- setup.py
- src/Controls/LingmoTabView.qml
> feat(LingmoTabView): add some functions

- example/qml/pages/TabView.qml
- setup.py
- src/Controls/LingmoTabView.qml
@elysia-best @chun-awa @lingmo-dream
> feat(LingmoTabView): add function for switching to tab

- .cmake/CheckForQtVersion/CMakeLists.txt
- .github/workflows/build.yml
- debian/control
- pyproject.toml
- setup.py
- src/Controls/LingmoNavigationView.qml
> fix: Add Qt6 SVG plugin dependency, optimize setup.py, remove redundant logs, upgrade Python version to 3.9

- .github/workflows/Auto CI Test Build.yml
- .github/workflows/build.yml
- .gitmodules
- CMakeLists.txt
- example/qml/global/SidebarItems.qml
- example/qml/main.qml
- example/qml/pages/HotkeyPicker.qml
- example/qml/windows/MainWindow.qml
- src/CMakeLists.txt
- src/Controls/LingmoHotkeyPicker.qml
- src/Controls/LingmoObject.qml
- src/Controls/LingmoRouter.qml
- src/LingmoApp.h
- src/LingmoHotkey.cpp
- src/LingmoHotkey.h
feature
No hotkey support
Added global hotkey registration support
No
**Note**: Currently does not support Wayland yet.
> feat(LingmoUI): add global Hotkey support

- example/qml/main.qml
- example/qml/windows/ShortcutWindow.qml
- src/LingmoHotkey.cpp
Bug fix
fix(LingmoHotkey): properly disconnect and delete hotkey on sequence change
feat(router): add hotkey route and ShortcutWindow component
> fix(Hotkey): fix pointer issue and callback

- .gitignore
- CHANGELOG.md
- Doxyfile
- debian/changelog
- setup.py
> chore: release 3.1.0

- example/qml/pages/TabView.qml
- src/Controls/LingmoTabView.qml
> feat(LingmoTabView): add a new property for accessing index 

- example/qml/pages/TabView.qml
- src/Controls/LingmoTabView.qml
> feat(LingmoTabView):add a function can access tab data by index

- CMakeLists.txt
> fix(CMakeLists.txt): add Qt Policy setting

- .github/workflows/build.yml
- debian/changelog
- setup.py
> chore: add tag events to build

- .github/workflows/build.yml
> chore: update Qt to 6.8.*

- .github/workflows/build.yml
> fix(ci): fix pypi upload

- src/LingmoTools.cpp
> fix: fix wallpaper path for KDE desktop session

- example/qml/pages/TabView.qml
- src/Controls/LingmoTabView.qml
> fix: change function to property to avoid error

- src/Controls/LingmoTabView.qml
> fix: make property readonly

- .github/workflows/build.yml
> !chore(ci): drop Python 3.9 support
